### ISSUE TITLE
Thoughts on using change_when: false for tasks with non-meaningful changes?

### ISSUE THREAD

**Issue by TravisWhitehead** [linuxhq/ansible-role-ius#6]
I've noticed that when using this role 3 tasks will be indicated as changed (when not run for the first time). These are:
```yams
- name: Attempting to generate temporary file
  tags: ius
  tempfile:
    prefix: 'ius.'
    state: file
    suffix: '.rpm'
  register: ius_tempfile
  check_mode: no

- name: Attempting to download package to temporary location
  tags: ius
  get_url:
    dest: "{{ ius_tempfile.path }}"
    force: yes
    url: "http://{{ ius_dist }}.iuscommunity.org/{{ ius_pkg }}.rpm"
  check_mode: no

...

- name: Attempting to purge temporary package from the filesystem
  tags: ius
  file:
    path: "{{ ius_tempfile.path }}"
    state: absent
```

However, knowing that these tasks changed is not particularly meaningful to my workflow, as I know it's just a temp file. Although it's true that the machine state has changed, it's not a change I care about (and sometimes causes me to scroll up thinking my ansible run has changed something more significant).

I'm not sure if this is bad practice, but what would y'all think about setting `changed_when: false` for these three tasks?

**Comment by tkimball83** [comment]
I have no issues with that change, please submit a pull request!
