### ISSUE TITLE
Tag/release for changes from #7

### ISSUE THREAD

**Issue by TravisWhitehead** [linuxhq/ansible-role-ius#8]
Hi @tkimball83, I noticed you merged #7 (thanks!) but I don't think a tag/release was created for that. Would be handy so folks can use versions for Ansible Galaxy instead of pointing to the `master` branch on GitHub.

Would you be willing to make a new release for what's currently in `master`?

**Comment by tkimball83** [comment]
Whoops, sorry about that!  Tag/release v0.0.9 has been created.

Please confirm all looks well from your end.  Thanks!

**Comment by TravisWhitehead** [comment]
Thanks. Looks good.
